### PR TITLE
clean up country and language props and moved translations

### PR DESCRIPTION
**Pull request by bonthebeerman**
optimized country and language props

### CODE REVIEW

**Comment by zburke** [comment]
I saw this PR sail by the other day and it got me wondering if we should have the country list in a central place, probably `stripes-core`. Currently we have it in `ui-users/translations` and here in `src/Utils/Country.js`. Consolidating both in `stripes-core` reduce duplication, and also allow it to be translatable for this module. What do you think?

**Comment by bonthebeerman** [comment]
I agree, it would be great to have country in one place.

**Comment by MikeTaylor** [comment]
It should be in a central place, yes. But I'm not sure stripes-core is it.

**Comment by zburke** [comment]
`stripes-components` then? Is there another candidate?

**Pull request merged**
