### PR TITLE
removed module name in package.json

### PR DESCRIPTION
**Pull request by bonthebeerman**

### CODE REVIEW

**Comment by MikeTaylor** [comment]
I'm interested -- why did you remove `moduleName`?

**Comment by bonthebeerman** [comment]
Hi Mike, got confused with displayName when I was updating. I thought moduleName is not needed. I'll  put back if its needed.

**Comment by MikeTaylor** [comment]
I've not looked deeply into this, but stripes-core does refer to `moduleName` in a few places.

**Comment by bonthebeerman** [comment]
thanks for looking into it. I will put back and at it to the rest of the site. thank you.

**Pull request merged**
